# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AEPSampleExtensionObjC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AEPSampleExtensionObjC

  pod 'AEPCore', :git => 'git@github.com:adobe/aepsdk-core-ios.git', :branch => 'main'
  pod 'AEPServices', :git => 'git@github.com:adobe/aepsdk-core-ios.git', :branch => 'main'
  pod 'AEPRulesEngine', :git => 'git@github.com:adobe/aepsdk-rulesengine-ios.git', :branch => 'main'

  target 'AEPSampleExtensionObjCTests' do
    # Pods for testing
  end

end
