# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AEPSampleExtensionObjC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AEPSampleExtensionObjC

  pod 'AEPCore', '~> 3.0'
  pod 'AEPServices', '~> 3.0'
  pod 'AEPRulesEngine', '~> 1.0'

  target 'AEPSampleExtensionObjCTests' do
    # Pods for testing
  end

end
