# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
use_frameworks!

target 'AEPSampleExtensionSwift' do
  pod 'AEPCore', '~> 3.0'
  pod 'AEPServices', '~> 3.0'
  pod 'AEPRulesEngine', '~> 1.0'

  target 'AEPSampleExtensionSwiftTests' do
  end

end
