# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
use_frameworks!

target 'AEPSampleExtensionSwift' do
  pod 'AEPCore', :git => 'git@github.com:adobe/aepsdk-core-ios.git', :branch => 'main'
  pod 'AEPServices', :git => 'git@github.com:adobe/aepsdk-core-ios.git', :branch => 'main'
  pod 'SwiftRulesEngine', :git => 'git@github.com:adobe/aepsdk-rulesengine-ios.git', :branch => 'dev'

  target 'AEPSampleExtensionSwiftTests' do
  end

end
